### ISSUE TITLE
Deploys 2.0

### ISSUE THREAD

**Issue by larouxn** [robwhitaker/MMPWebsiteV2#116]
Deploys need to be overhauled and/or replaced with smaller scripts or something. The current stacks is simply untenable.

**Comment by larouxn** [comment]
Basically need to create some sort of playbook for how to deploy. It's super straightforward but I should write it up and/or create a script.

**Comment by robwhitaker** [comment]
Not happening.

**Comment by larouxn** [comment]
Can confirm.
