### ISSUE TITLE
Share Buttons

### ISSUE THREAD

**Issue by Rillalynn** [robwhitaker/MMPWebsiteV2#132]
Share buttons don't exist in Safari on iOS. 
![img_1509](https://user-images.githubusercontent.com/19582682/27159633-69305c84-513c-11e7-81e5-89f0395a2fdb.PNG)
![img_1510](https://user-images.githubusercontent.com/19582682/27159634-693726a4-513c-11e7-8410-eac376a45ab2.PNG)

**Comment by robwhitaker** [comment]
Possible fix: `-webkit-transform:translateZ(0);`
