### ISSUE TITLE
Header button link at top of page does not navigate when clicked

### ISSUE THREAD

**Issue by johnpaulwelsh** [robwhitaker/MMPWebsiteV2#147]
Device: Macbook Pro 2015
OS: Mac OS X 10.14.5 64-bit
Browser: Opera Developer 61.0.3282.0
**Also seen on XBox One Microsoft Edge, not limited to one system or browser**

When I am on any page of the site, if I click on the image banner at the top which says Midnight Murder Party, I expect it to navigate me to the home page, but instead nothing happens. I have tried this while on the home page already, and also some subheadings such as [http://beta.midnightmurderparty.com/#!/c2](http://beta.midnightmurderparty.com/#!/c2).

It works fine if I open the link in a new tab instead of the current tab.

Note from Rob: "Probably introduced by the new navigation changes in 0.19."

**Comment by robwhitaker** [comment]
This has now been addressed on the [elm-0.19-upgrade](https://github.com/robwhitaker/mmp-website/tree/elm-0.19-upgrade) branch.
