### ISSUE TITLE
TOC label positioned poorly in some cases

### ISSUE THREAD

**Issue by robwhitaker** [robwhitaker/MMPWebsiteV2#15]
![image](https://cloud.githubusercontent.com/assets/2818781/17722973/47994570-6404-11e6-928f-54e5e3ebd065.png)
The text should be vertically centered (level with the arrow), not pushing against the bottom of its container. This only seems to occur on my desktop. Browser and window size don't seem to matter.

**Comment by larouxn** [comment]
I highly recommend `padding: 0.25em 1em;` 👌

**Comment by robwhitaker** [comment]
Still doesn't work cross-device.
