### ISSUE TITLE
Instant window resize leads to &nnbsp; appearing in text

### ISSUE THREAD

**Issue by johnpaulwelsh** [robwhitaker/MMPWebsiteV2#3]
Opera Developer 39.0.2234.0
1. Clicked on dropdown heading for Episode 2-2A-6
2. Did keyboard shortcut to instant change size of window (shorter)
3. "&nnbsp;" shows up at beginning of paragraph in section 6
4. Resized back to full-screen and it's still there
5. Turn page backwards, turn forward again, text is still there
   ![resizenonsense](https://cloud.githubusercontent.com/assets/2716203/15522787/c79a5660-21e2-11e6-8b18-58f4e8bf494f.jpg)

**Comment by johnpaulwelsh** [comment]
Pretty sure that text is there no matter what. The extra 'n' is un-escaping the &nbsp;

**Comment by robwhitaker** [comment]
Was actually a typo in fixture data. Ignore.
