### ISSUE TITLE
GitHub Auto Deploy (if possible)

### ISSUE THREAD

**Issue by robwhitaker** [robwhitaker/MMPWebsiteV2#32]

**Comment by larouxn** [comment]
Unfortunately, this does not seem reasonable, possible, or necessary with our current tech stack. Closing this in favour of simply having both of our machines one command away from deploying at any moment.

**Comment by robwhitaker** [comment]
@larouxn - Brace for perpetual deploy requests!

**Comment by larouxn** [comment]
Well, I kinda figured we could simply add your public SSH key to the server and you could run the deploy command but if not, sure, I'll run some deploy commands for ya. ¯\\__(ツ)_/¯
