### ISSUE TITLE
Halloween

### ISSUE THREAD

**Issue by Rillalynn** [robwhitaker/MMPWebsiteV2#4]
So, the Halloween part opens in the reader but its super difficult to navigate and terrible 
![image](https://cloud.githubusercontent.com/assets/19582682/15562364/90d766dc-22cc-11e6-8b42-ee0b3c06f135.png)

Also at this point you can't navigate anywhere else.

**Comment by robwhitaker** [comment]
Fixed with 58fa654e2c7b60bbb7.
