### ISSUE TITLE
Show low-res images first until high-res versions load

### ISSUE THREAD

**Issue by robwhitaker** [robwhitaker/MMPWebsiteV2#66]
On slow connections, this will hopefully cause a close-to-immediate display of all images in low resolution while the high resolution images load in the background, making the site immediately usable.

**Comment by robwhitaker** [comment]
@larouxn - when you get a chance, could you make some really low-res versions of the main images (background, logo, book cover, book back) and upload them to a new branch for this enhancement? Tiny and pixelated is fine, as long as the images load pretty much immediately even on a slow connection.

**Comment by larouxn** [comment]
@robwhitaker, images have been committed and pushed up to a branch called [low_res_image_swap](https://github.com/robwhitaker/mmp-website/tree/low_res_image_swap).
