### ISSUE TITLE
iOS Safari app loads wrong page when selecting an act from the drop down menu

### ISSUE THREAD

**Issue by Rillalynn** [robwhitaker/MMPWebsiteV2#77]
![img_0750](https://cloud.githubusercontent.com/assets/19582682/22005604/ab853af2-dc32-11e6-8667-f193d41336ff.PNG)
Clicked 2C, got the last page of 2B. Problem only appears to exist in Safari.

**Comment by robwhitaker** [comment]
Added an extra check, but can't reproduce anyway.
