### ISSUE TITLE
iOS chrome incognito rendering problems. 

### ISSUE THREAD

**Issue by Rillalynn** [robwhitaker/MMPWebsiteV2#78]
![img_0752](https://cloud.githubusercontent.com/assets/19582682/22006504/a08ac6ce-dc39-11e6-98f2-7373fe708a71.PNG)
Rendering in Chrome is fine in normal browsing but doesn't work in incognito mode. 
![img_0871](https://cloud.githubusercontent.com/assets/19582682/23392621/05753a56-fd4b-11e6-80ca-8a09154296f4.PNG)

**Comment by Rillalynn** [comment]
Issue also appears on Safari incognito. Navigation of about two pages is manageable before the message pops up again after refreshing.

**Comment by robwhitaker** [comment]
Error caused by using `localStorage` in incognito. More info here: http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st .
