### ISSUE TITLE
Chrome iOS reflowing

### ISSUE THREAD

**Issue by Rillalynn** [robwhitaker/MMPWebsiteV2#98]
When clicking on text or the share button after it is closed, the reflowing message appears and you are then taken back a page.

**Comment by robwhitaker** [comment]
From Slack:
"If you're at the top of the page in chrome the URL is always visible. If you scroll down it isn't. The reflowing is not changing the visibility of the URL bar. It sometimes just does it once but other times goes on a loop.

And a good paragraph ends up highlighted in yellow.

Actually. May be right with the URL. It tends to refresh in the top and middle when scrolling up from the bottom right as the URL bar should be appearing again on closer inspection."
